### ISSUE TITLE
Memory fault, involving XMLBase

### ISSUE THREAD

**Issue by skuzzymiglet** [mmcdole/gofeed#159]
### Expected behavior

Correctly parse feed

### Actual behavior

A memory fault occurs (1 in 2 times). Here's part of the panic:

```
goroutine 42 [running]:
runtime.throw(0x93c18a, 0x5)
	/usr/lib/go/src/runtime/panic.go:1116 +0x72 fp=0xc0004399b8 sp=0xc000439988 pc=0x4376d2
runtime.sigpanic()
	/usr/lib/go/src/runtime/signal_unix.go:727 +0x405 fp=0xc0004399e8 sp=0xc0004399b8 pc=0x44d305
net/url.validEncoded(0x97c31b1be2a3f066, 0x55d13db2, 0x1, 0xc000b8d200)
	/usr/lib/go/src/net/url/url.go:723 +0x40 fp=0xc000439a18 sp=0xc0004399e8 pc=0x5e1320
net/url.(*URL).EscapedPath(0xc0002a5640, 0xc000b8d290, 0xc000b8d200)
	/usr/lib/go/src/net/url/url.go:701 +0x14c fp=0xc000439a60 sp=0xc000439a18 pc=0x5e12ac
net/url.(*URL).ResolveReference(0xc0002a5640, 0xc000b8d200, 0xc000b8d200)
	/usr/lib/go/src/net/url/url.go:1075 +0x278 fp=0xc000439ab8 sp=0xc000439a60 pc=0x5e41d8
github.com/mmcdole/gofeed/internal/shared.(*XMLBase).push(0xc000a7c280, 0x0, 0x0, 0x0, 0xc000b86b80)
	/home/skuzzymiglet/.local/go/pkg/mod/github.com/mmcdole/gofeed@v1.1.0/internal/shared/xmlbase.go:148 +0x1d8 fp=0xc000439b30 sp=0xc000439ab8 pc=0x7bd358
github.com/mmcdole/gofeed/internal/shared.(*XMLBase).NextTag(0xc000a7c280, 0xc000397950, 0xc000b96c00, 0x0, 0x0)
	/home/skuzzymiglet/.local/go/pkg/mod/github.com/mmcdole/gofeed@v1.1.0/internal/shared/xmlbase.go:109 +0xe9 fp=0xc000439b80 sp=0xc000439b30 pc=0x7bcf49
github.com/mmcdole/gofeed/atom.(*Parser).parseEntry(0xc000010360, 0xc000397950, 0xc000b86b2a, 0x5, 0x0)
	/home/skuzzymiglet/.local/go/pkg/mod/github.com/mmcdole/gofeed@v1.1.0/atom/parser.go:224 +0x174 fp=0xc000439cb8 sp=0xc000439b80 pc=0x7df494
github.com/mmcdole/gofeed/atom.(*Parser).parseRoot(0xc000010360, 0xc000397950, 0x2, 0x0, 0x0)
	/home/skuzzymiglet/.local/go/pkg/mod/github.com/mmcdole/gofeed@v1.1.0/atom/parser.go:170 +0xa17 fp=0xc000439de8 sp=0xc000439cb8 pc=0x7de4f7
github.com/mmcdole/gofeed/atom.(*Parser).Parse(0xc000010360, 0x9c6e20, 0xc0005ea860, 0x8d4d40, 0xc0005ea801, 0xc0005ea860)
	/home/skuzzymiglet/.local/go/pkg/mod/github.com/mmcdole/gofeed@v1.1.0/atom/parser.go:50 +0xf0 fp=0xc000439e28 sp=0xc000439de8 pc=0x7dda90
github.com/mmcdole/gofeed.(*Parser).parseAtomFeed(0xc000074320, 0x9c6e20, 0xc0005ea860, 0xc000439eb0, 0xc0005ea840, 0x0)
	/home/skuzzymiglet/.local/go/pkg/mod/github.com/mmcdole/gofeed@v1.1.0/parser.go:133 +0x47 fp=0xc000439e68 sp=0xc000439e28 pc=0x7ebc47
github.com/mmcdole/gofeed.(*Parser).Parse(0xc000074320, 0x7f1b145b35b8, 0xc000877230, 0x7f1b145b35b8, 0xc000877230, 0x0)
	/home/skuzzymiglet/.local/go/pkg/mod/github.com/mmcdole/gofeed@v1.1.0/parser.go:73 +0x279 fp=0xc000439ee0 sp=0xc000439e68 pc=0x7eb339
git.sr.ht/~skuzzymiglet/feef/feeds.(*Feeds).Fetch(0xc00017df50, 0xc0001e2730, 0x4c, 0x0, 0x0)
	/home/skuzzymiglet/code/feef/feeds/feeds.go:77 +0xc7 fp=0xc000439f58 sp=0xc000439ee0 pc=0x7f1f67
main.main.func1.1(0xc00017df50, 0xc0000760c0, 0xc0001e2730, 0x4c, 0xc00008e000)
	/home/skuzzymiglet/code/feef/main.go:74 +0x6e fp=0xc000439fb8 sp=0xc000439f58 pc=0x867a4e
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc000439fc0 sp=0xc000439fb8 pc=0x46ca21
created by main.main.func1
	/home/skuzzymiglet/code/feef/main.go:72 +0xf5

```

### Steps to reproduce the behavior

I'm not sure

Note: Please include any links to problem feeds, or the feed content itself!

**Comment by mmcdole** [comment]
Can you please link to the feed in question?

**Comment by skuzzymiglet** [comment]
Non-deterministic, I think. It also seems to happen only with concurrent use. Are you testing concurrency in the package?

**Comment by genert** [comment]
The issue still exists. When using parser concurrently, it will throw the error.

Does the library hold any kind of internal state?

As a remedy, use `sync.Pool`:

```go
type myImpl struct {

}

func NewMyImpl() {
    return &myImpl{
        feedParserPool: sync.Pool{
	      New: func() interface{} {
		      return gofeed.NewParser()
	      },
      },
    }
}

// ...
fp := impl.feedParserPool.Get().(*gofeed.Parser)
feed, err := fp.ParseURL("https://my-url.com/feed")
// ...
impl.feedParserPool.Put(fp)
```

**Comment by Necoro** [comment]
Stumbling over this issue: Yes, the parser holds internal state (cf. internal/shared/xmlbase). Question is: What is the purpose of using the same parser instance twice? Why not instantiate a new parser for each parse?

@mmcdole: What is your intention? Perhaps it's sufficient to just add documentation that a Parser should not be shared.

**Comment by mmcdole** [comment]
I think this has been resolved by @cristoper 's latest patch to XPP + gofeed.  If someone runs into this again, please let me know and I'll re-open the issue.
